url: 'https://speller.yandex.net/services/spellservice?WSDL'
url2: 'https://test-stand.gb.ru/gateway/login'
login: 'kitty89'
password: '61d96a3985'
url_post: 'https://test-stand.gb.ru/api/posts'
login_page: 'https://test-stand.gb.ru/login'
